[mypy]
warn_unused_configs = True
check_untyped_defs = True
packages = src.license_mole
# disallow_untyped_defs demands -> None, allow other linters to handle this
warn_redundant_casts = True
warn_unused_ignores = True
extra_checks = True
