# vim: ts=3 sts=3 sw=3 expandtab:
"""Rendering labels and templates.

Copyright (c) 2025 Posit Software, PBC
SPDX-License-Identifier: MIT

Use this file to change the text displayed for package types and license names.
"""

PACKAGE_TYPES = {
   'npm': ' (npm package)',
   'go': ' (Go package)',
   'rust': ' (Rust package)',
   'py': ' (Python package)',
}

LICENSE_SHORT_NAMES = {
   '0BSD': '0BSD',
   'AFL-2.1': 'AFLv2.1',
   'AGPL-3.0': 'AGPLv3',
   'AGPL-3.0-ONLY': 'AGPLv3',
   'APACHE-2.0': 'Apache',
   'APACHE-2.0-WITH-LLVM-EXCEPTION': 'Apache',
   'APACHE-2.0-WITH-LLVM-EXCEPTIONS': 'Apache',
   'ARTISTIC-2.0': 'Artistic',
   'BLUEOAK-1.0.0': 'BlueOak',
   'BORINGSSL': 'BoringSSL',
   'BSD-2-CLAUSE': 'BSD',
   'BSD-3-CLAUSE': 'BSD',
   'BSD-3-CLAUSE-WITH-PCRE2-EXCEPTION': 'BSD',
   'BSL-1.0': 'Boost',
   'BZIP2': 'bzip2',
   'CC-BY-3.0': 'CC BY 3.0',
   'CC-BY-4.0': 'CC BY 4.0',
   'CC0-1.0': 'CC0',
   'CPL-1.0': 'CPL',
   'CURL': 'curl',
   'GPL-2.0': 'GPLv2',
   'GPL-2.0-ONLY': 'GPLv2',
   'GPL-2.0-OR-LATER': 'GPLv2+',
   'GPL-3.0': 'GPLv3',
   'HPND': 'HPND',
   'ISC': 'ISC',
   'LGPL-2.0': 'LGPLv2',
   'LGPL-2.0-OR-LATER': 'LGPLv2+',
   'LGPL-2.1': 'LGPLv2.1',
   'LGPL-2.1-OR-LATER': 'LGPLv2.1+',
   'LGPL-3.0': 'LGPLv3',
   'MIT': 'MIT',
   'MIT-WITH-ADDITIONAL': 'MIT',
   'MPL-1.0': 'MPLv1',
   'MPL-2.0': 'MPLv2',
   'OFL-1.1': 'OFL',
   'POSTGRESQL': 'PostgreSQL',
   'PUBLIC-DOMAIN': 'public domain',
   'PYTHON-2.0': 'Python',
   'PSF-2.0': 'Python',
   'SQLITE-BLESSING': 'public domain',
   'UNICODE-3.0': 'Unicode v3',
   'UNICODE-DFS-2016': 'Unicode-DFS',
   'UNLICENSE': 'Unlicense',
   'WTFPL': 'WTFPL',
   'ZLIB': 'zlib',
   'ZOPE': 'Zope',
}

LICENSE_NAMES = {
   '0BSD': '0BSD License',
   'AFL-2.1': 'Academic Free License version 2.1',
   'AGPL-3.0': 'GNU Affero General Public License version 3.0',
   'AGPL-3.0-ONLY': 'GNU Affero General Public License version 3.0',
   'APACHE-2.0': 'Apache License version 2.0',
   'APACHE-2.0-WITH-LLVM-EXCEPTION': 'Apache License version 2.0 with LLVM Exceptions',
   'APACHE-2.0-WITH-LLVM-EXCEPTIONS': 'Apache License version 2.0 with LLVM Exceptions',
   'ARTISTIC-2.0': 'Artistic License version 2.0',
   'BLUEOAK-1.0.0': 'Blue Oak Model License version 1.0.0',
   'BORINGSSL': 'BoringSSL license',
   'BSD-2-CLAUSE': 'BSD 2-Clause license',
   'BSD-3-CLAUSE': 'BSD 3-Clause license',
   'BSD-3-CLAUSE-WITH-PCRE2-EXCEPTION': 'BSD 3-Clause license with PCRE2 Exception',
   'BSL-1.0': 'Boost Software License',
   'BZIP2': 'bzip2 License',
   'CC0-1.0': 'CC0 1.0 Universal',
   'CC-BY-3.0': 'Creative Commons Attribution 3.0',
   'CC-BY-4.0': 'Creative Commons Attribution 4.0',
   'CPL-1.0': 'Common Public License',
   'CURL': 'curl License',
   'GPL-2.0': 'GNU General Public License version 2.0',
   'GPL-2.0-ONLY': 'GNU General Public License version 2.0',
   'GPL-2.0-OR-LATER': 'GNU General Public License version 2.0 or later',
   'GPL-3.0': 'GNU General Public License version 3.0',
   'HPND': 'Historical Permission Notice and Disclaimer',
   'ISC': 'ISC License',
   'LGPL-2.0': 'GNU Library General Public License version 2.0',
   'LGPL-2.0-OR-LATER': 'GNU Library General Public License version 2.0 or later',
   'LGPL-2.1': 'GNU Lesser General Public License version 2.1',
   'LGPL-2.1-OR-LATER': 'GNU Lesser General Public License version 2.1 or later',
   'LGPL-3.0': 'GNU Lesser General Public License version 3.0',
   'MIT': 'MIT License',
   'MIT-WITH-ADDITIONAL': 'MIT License and additional licenses',
   'MPL-1.0': 'Mozilla Public License version 1.0',
   'MPL-2.0': 'Mozilla Public License version 2.0',
   'OFL-1.1': 'SIL Open Font License',
   'POSTGRESQL': 'PostgreSQL License',
   'PSF-2.0': 'Python Software Foundation License version 2.0',
   'PYTHON-2.0': 'Python License version 2.0',
   'UNICODE-3.0': 'Unicode License v3',
   'UNICODE-DFS-2016': 'Unicode Data Files and Software License Agreement (2016)',
   'UNLICENSE': 'Unlicense',
   'WTFPL': 'WTFPL',
   'ZLIB': 'zlib License',
   'ZOPE': 'Zope License',
}

LICENSE_MESSAGES = {
   'CC0-1.0': 'Released using [CC0](#CC0-1.0)',
   'PUBLIC-DOMAIN': '',
   'SQLITE-BLESSING': '',
   'UNLICENSE': 'Distributed under the Unlicense',
}
